version: '3'
services:
  supportbot:
    build: .
    #image: "bostrot/telegram-support-bot:latest"
    restart: unless-stopped
    volumes:
      - ./config:/bot/config
    ports:
      - "8080:8080"
